# Generated by Django 3.2.7 on 2021-09-13 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210913_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_serving_kca', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('sodium_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('saturated', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('sugars_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('caffeine_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('size_ml', models.CharField(max_length=45, null=True)),
                ('size_fluid_ounce', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.menu'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.nutrition'),
        ),
    ]
