# Generated by Django 3.2.7 on 2021-09-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210913_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='caffeine_mg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='one_serving_kca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='saturated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sodium_mg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugars_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
