# Generated by Django 3.2.7 on 2021-09-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
