# Generated by Django 3.2.7 on 2021-09-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_allergy_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='products',
            new_name='allergy_product',
        ),
    ]
