# Generated by Django 3.2.7 on 2021-09-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_products_allergy_allergy_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='allergy_product',
            new_name='product',
        ),
    ]
