# Generated by Django 3.2.7 on 2021-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_allergy_product_allergy_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='product',
            field=models.ManyToManyField(related_name='allergies', to='products.Product'),
        ),
    ]
