# Generated by Django 3.2.7 on 2021-09-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_allergy_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='product',
            new_name='products',
        ),
    ]
